export const DIRECCION = "Guadalajara, Mexico, 44100";
export const NOMBRE = "Selección AMDI Jalisco";
export const NOMBRE_CORTO = "AMDI";
export const NOMBRE_COMPLETO = "Asociación Mexicana de Desarrollo Motriz Infantil"
export const TELEFONO = "3317752653"
export const CORREO = "17soccer.life@gmail.com"
export const HORARIO_INCIO = "08:00"
export const HORARIO_CIERRE = "21:00"
export const HORARIO_DIA_INICIO = "lunes"
export const HORARIO_DIA_CIERRE = "sabado"
